# Analiza momčadi

Analiza prikazuje preformanse momčadi u natjecanjima

### Opis tablice
* ID momčadi
* Ime momčadi
* Ukupan broj bodova (score)
* Broj pobjeda/poraza/izjednačenih utakmica (W/L/D)
* Broj pobjeda s obzirom na home / away
* Ukupan broj utakmica (totalMatches)
* Ukupan broj primljenih pogodaka (goalsScored) 
* Ukupan broj pogodaka (goalsRecived) 


### TODO
* Napraviti graf ko je s kime igrao
* Izračunati score

In [25]:
import numpy as np
import seaborn as sns
import pandas as pd
from pandas import Series,DataFrame
import os

#Dohvacanje CSV datoteke za utakmice 
fileDirU = os.path.dirname(os.path.realpath('mozgalo_gladbach_eintracht_utakmice.csv'))
filenameU = os.path.join(fileDirU, '../../data/clean/mozgalo_gladbach_eintracht_utakmice.csv')
fileU = os.path.abspath(os.path.realpath(filenameU))

#Dohvacanje CSV datoteke za akcije
fileDirA = os.path.dirname(os.path.realpath('mozgalo_gladbach_eintracht_akcije.csv'))
filenameA = os.path.join(fileDirA, '../../data/clean/mozgalo_gladbach_eintracht_akcije.csv')
fileA = os.path.abspath(os.path.realpath(filenameA))

In [26]:
dframe_utakmice = pd.read_csv(fileU, sep=",")
dframe_akcije = pd.read_csv(fileA, sep=",")

In [27]:
momcadiA = dframe_utakmice[['domaci','domaciID',]]
momcadiB = dframe_utakmice[['gosti','gostiID']]

In [28]:
momcadiA= momcadiA.drop_duplicates()
mocadiA = momcadiA.reset_index(drop=True, inplace=True)
momcadiA.columns = ['name','ID']
momcadiA

                   name     ID
0   Eintracht Frankfurt  10347
1         VfL Wolfsburg  10653
2            Hertha BSC  10437
3    Borussia Mgladbach  10307
4           FC Augsburg  10269
5          Hamburger SV  10419
6            1. FC Koln  10476
7       1. FSV Mainz 05  10388
8     Borussia Dortmund  10303
9   Bayer 04 Leverkusen  10281
10      Manchester City   9259
11  TSG 1899 Hoffenheim  10442

In [29]:
momcadiB = momcadiB.drop_duplicates()
momcadiB.reset_index(drop=True, inplace=True)
momcadiB.columns = ['name','ID']
momcadiB

                   name     ID
0      FC Ingolstadt 04  10453
1    Borussia Mgladbach  10307
2   Eintracht Frankfurt  10347
3         VfB Stuttgart  10646
4         FC Schalke 04  10576
5            1. FC Koln  10476
6          Hamburger SV  10419
7      SV Werder Bremen  10677
8         VfL Wolfsburg  10653
9     Borussia Dortmund  10303
10      SV Darmstadt 98  10329
11    FC Bayern Munchen  10285
12           Sevilla CF  16175
13  Bayer 04 Leverkusen  10281
14          Hannover 96  10423

In [30]:
result = momcadiA.append(momcadiB)
result.drop_duplicates(inplace=True)
result.reset_index(drop=True, inplace=True)
result

                   name     ID
0   Eintracht Frankfurt  10347
1         VfL Wolfsburg  10653
2            Hertha BSC  10437
3    Borussia Mgladbach  10307
4           FC Augsburg  10269
5          Hamburger SV  10419
6            1. FC Koln  10476
7       1. FSV Mainz 05  10388
8     Borussia Dortmund  10303
9   Bayer 04 Leverkusen  10281
10      Manchester City   9259
11  TSG 1899 Hoffenheim  10442
12     FC Ingolstadt 04  10453
13        VfB Stuttgart  10646
14        FC Schalke 04  10576
15     SV Werder Bremen  10677
16      SV Darmstadt 98  10329
17    FC Bayern Munchen  10285
18           Sevilla CF  16175
19          Hannover 96  10423

In [31]:
test = dframe_utakmice[['domaci','Score_domaci','gosti','Score_gosti', 'Pogodaka_domaci','Pogodaka_gosti',]]
test

,domaci,Score_domaci,gosti,Score_gosti,Pogodaka_domaci,Pogodaka_gosti
0,Eintracht Frankfurt,1,FC Ingolstadt 04,1,1,1
1,VfL Wolfsburg,3,Borussia Mgladbach,0,2,1
2,Hertha BSC,3,Eintracht Frankfurt,0,2,0
3,Borussia Mgladbach,3,VfB Stuttgart,0,4,0
4,Eintracht Frankfurt,1,FC Schalke 04,1,0,0
5,FC Augsburg,1,Borussia Mgladbach,1,2,2
6,Borussia Mgladbach,3,1. FC Koln,0,1,0
7,Eintracht Frankfurt,1,Hamburger SV,1,0,0
8,Hamburger SV,3,Borussia Mgladbach,0,3,2
9,1. FC Koln,3,Eintracht Frankfurt,0,3,1
10,Eintracht Frankfurt,0,VfB Stuttgart,3,2,4
11,Borussia Mgladbach,3,SV Werder Bremen,0,5,1
12,FC Augsburg,1,Eintracht Frankfurt,1,0,0
13,1. FSV Mainz 05,3,Borussia Mgladbach,0,1,0
14,Eintracht Frankfurt,3,VfL Wolfsburg,0,3,2
15,Borussia Mgladbach,0,Borussia Dortmund,3,1,3
16,Borussia Mgladbach,3,SV Darmstadt 98,0,3,2
17,Eintracht Frankfurt,3,SV Werder Bremen,0,2,1
18,Borussia Dortmund,3,Eintracht Frankfurt,0,4,1
19,Bayer 04 Leverkusen,3,Borussia Mgladbach,0,5,0
20,Manchester City,3,Borussia Mgladbach,0,4,2
21,Eintracht Frankfurt,0,SV Darmstadt 98,3,0,1
22,Borussia Mgladbach,3,FC Bayern Munchen,0,3,1
23,1. FSV Mainz 05,3,Eintracht Frankfurt,0,2,1
24,TSG 1899 Hoffenheim,1,Borussia Mgladbach,1,3,3
25,Borussia Mgladbach,3,Sevilla CF,0,4,2
26,Eintracht Frankfurt,0,Bayer 04 Leverkusen,3,1,3
27,Borussia Mgladbach,3,Hannover 96,0,2,1
28,Borussia Mgladbach,1,FC Ingolstadt 04,1,0,0
29,TSG 1899 Hoffenheim,1,Eintracht Frankfurt,1,0,0

In [32]:
for index, item in result.iterrows():
    formH = ""
    form = ""
    formA = ""
    f = 0
    l = 0
    #home lose
    hl = 0
    #away lose
    al = 0
    #total wins
    w = 0
    #home 
    hw = 0
    aw = 0
    d = 0
    hd = 0
    ad = 0
    totalGoals = 0
    primljeni = 0
    for i, row in test.iterrows():
        if item["name"] == row['domaci']:
            if row['Score_domaci'] == 0:
                l = l + 1
                hl = hl + 1
                form += "l"
                formH += "l"
            if row['Score_domaci'] == 1:
                d = d + 1
                hd = hd + 1
                form += "d"
                formH += "d"

            if row['Score_domaci'] == 3:
                w = w + 1
                hw = hw + 1
                form += "w"
                formH += "w"

            totalGoals = totalGoals + row['Pogodaka_domaci']
            primljeni = primljeni + row['Pogodaka_gosti']
            f = f +row["Score_domaci"]
            #print (item["name"])
            #print (f)
        if item["name"] == row['gosti']:
            if row['Score_gosti'] == 0:
                l = l + 1
                al = al + 1
                form += "l"
                formA += "l"
            if row['Score_gosti'] == 1:
                d = d + 1
                ad = ad + 1
                form += "d"
                formA += "d"
            if row['Score_gosti'] == 3:
                w = w + 1
                aw = aw + 1
                form += "w"
                formA += "w"
            f = f+ row["Score_gosti"]
            totalGoals = totalGoals + row['Pogodaka_gosti']
            primljeni = primljeni + row['Pogodaka_domaci']
    #print (item["name"] + ": " + str(f))
    #print ("w=" + str(w) + ", l="+ str(l) + ", d=" + str(d))
    result.ix[index,"w"] = w
    result.ix[index,"l"] = l
    result.ix[index,"d"] = d

    #print ("hw=" + str(hw) + ", hl=" + str(hl) + ", hd=" + str(hd))
    result.ix[index,"hw"] = hw
    result.ix[index,"hl"] = hl
    result.ix[index,"hd"] = hd

    #print ("aw=" + str(aw) + ", al=" + str(al) + ", ad=" + str(ad))
    result.ix[index,"aw"] = aw
    result.ix[index,"al"] = al
    result.ix[index,"ad"] = ad
    
    #print ("Ukupan broj utakmica: " + str(w+l+d))
    result.ix[index,"totalMatches"] = w+l+d
    
    #print ("Ukupan broj golova: " + str(totalGoals))
    result.ix[index,"goalsScored"] = totalGoals
    
    #print ("Ukupan broj primljenih pogodaka: " + str(primljeni))
    result.ix[index,"goalsRecived"] = primljeni
    
    result.ix[index,"form"] = form
    result.ix[index,"formA"] = formA
    result.ix[index,"formH"] = formH
    

    #print ('\n')

In [33]:
#result

In [34]:
#result["goalRatio"] = result.goalsScored/result.goalsRecived

In [38]:
result.sort_values("goalsScored",ascending=False)
result.reset_index(drop=True,inplace=True)
result

,name,ID,w,l,d,hw,hl,hd,aw,al,ad,totalMatches,goalsScored,goalsRecived,form,formA,formH
0,Eintracht Frankfurt,10347,2,7,5,2,3,3,0,4,2,14,12,23,dlddlldwwlllld,lldlld,dddlwwll
1,VfL Wolfsburg,10653,1,1,0,1,0,0,0,1,0,2,4,4,wl,l,w
2,Hertha BSC,10437,1,0,0,1,0,0,0,0,0,1,2,0,w,,w
3,Borussia Mgladbach,10307,7,6,3,7,1,1,0,5,2,16,33,30,lwdwlwllwllwdwwd,ldlllld,wwwlwwwwd
4,FC Augsburg,10269,0,0,2,0,0,2,0,0,0,2,2,2,dd,,dd
5,Hamburger SV,10419,1,0,1,1,0,0,0,0,1,2,3,2,dw,d,w
6,1. FC Koln,10476,1,1,0,1,0,0,0,1,0,2,3,2,lw,l,w
7,1. FSV Mainz 05,10388,2,0,0,2,0,0,0,0,0,2,3,1,ww,,ww
8,Borussia Dortmund,10303,2,0,0,1,0,0,1,0,0,2,7,2,ww,w,w
9,Bayer 04 Leverkusen,10281,2,0,0,1,0,0,1,0,0,2,8,1,ww,w,w
10,Manchester City,9259,1,0,0,1,0,0,0,0,0,1,4,2,w,,w
11,TSG 1899 Hoffenheim,10442,0,0,2,0,0,2,0,0,0,2,3,3,dd,,dd
12,FC Ingolstadt 04,10453,0,0,2,0,0,0,0,0,2,2,1,1,dd,dd,
13,VfB Stuttgart,10646,1,1,0,0,0,0,1,1,0,2,4,6,lw,lw,
14,FC Schalke 04,10576,0,0,1,0,0,0,0,0,1,1,0,0,d,d,
15,SV Werder Bremen,10677,0,2,0,0,0,0,0,2,0,2,2,7,ll,ll,
16,SV Darmstadt 98,10329,1,1,0,0,0,0,1,1,0,2,3,3,lw,lw,
17,FC Bayern Munchen,10285,0,1,0,0,0,0,0,1,0,1,1,3,l,l,
18,Sevilla CF,16175,0,1,0,0,0,0,0,1,0,1,2,4,l,l,
19,Hannover 96,10423,0,1,0,0,0,0,0,1,0,1,1,2,l,l,

In [39]:
result.to_csv("team_stats.csv")