In [18]:
import numpy as np
import seaborn as sns
import pandas as pd
from pandas import Series,DataFrame
import os

#Dohvacanje CSV datoteke za utakmice 
fileDirU = os.path.dirname(os.path.realpath('mozgalo_gladbach_eintracht_utakmice.csv'))
filenameU = os.path.join(fileDirU, '../../data/clean/mozgalo_gladbach_eintracht_utakmice.csv')
fileU = os.path.abspath(os.path.realpath(filenameU))

#Dohvacanje CSV datoteke za akcije
fileDirA = os.path.dirname(os.path.realpath('mozgalo_gladbach_eintracht_akcije.csv'))
filenameA = os.path.join(fileDirA, '../../data/clean/mozgalo_gladbach_eintracht_akcije.csv')
fileA = os.path.abspath(os.path.realpath(filenameA))


#Dohvacanje XLSX datoteke za akcije
fileDirC = os.path.dirname(os.path.realpath('Once - Lista akcija.xlsx'))
filenameC = os.path.join(fileDirA, '../../data/clean/Once - Lista akcija.xlsx')
fileC = os.path.abspath(os.path.realpath(filenameC))

#Dohvacanje XLSX datoteke za pozicije igrača
fileDirD = os.path.dirname(os.path.realpath('once_player_position.xlsx'))
filenameD = os.path.join(fileDirD, '../../data/clean/once_player_position.xlsx')
fileD = os.path.abspath(os.path.realpath(filenameD))

In [19]:
dframe_ef = pd.read_excel("efPlayers.xls")
dframe_efActionsByGame = pd.read_excel("eintrachtFrankfurtSveAkcije.xls")
dframe_akcije = pd.read_csv(fileA)

In [21]:
for item in dframe_akcije["actionID"].unique():
    dframe_ef[str(item)] = 0

In [22]:
for indexA, itemA in dframe_ef.iterrows():
    for indexB, itemB in dframe_akcije.iterrows():
        if (itemA["playerID"] == itemB["playerID"]):
            dframe_ef.loc[indexA,str(itemB.actionID)] +=1

In [23]:
dframe_ef

,playerID,name,position1,position2,position3,position4,position5,position6,appearances,247,...,353,216,62,52,20,26,91,99,16,163
0,212914,Y. Regasel,RB,RWB,RCB,NaN,NaN,NaN,5,168,...,0,0,0,0,0,0,0,0,0,0
1,199745,M. Stendera,LCM,RCM,CAM,NaN,NaN,NaN,12,492,...,0,0,0,0,0,0,0,0,0,0
2,1802,A. Meier,CAM,ST,LCM,LCF,NaN,NaN,11,177,...,0,1,0,0,0,0,0,0,0,0
3,22870,M. Fabian,CAM,ST,LCM,LCF,NaN,NaN,8,294,...,1,0,0,0,0,0,0,0,0,0
4,1770,S. Huszti,LW,CAM,LCM,NaN,NaN,NaN,8,306,...,0,0,0,0,0,0,0,0,0,0
5,206101,G. Waldschmidt,LCM,LW,RB,NaN,NaN,NaN,4,34,...,0,0,0,0,0,0,0,0,0,0
6,196633,B. Oczipka,LB,LWB,LW,NaN,NaN,NaN,13,605,...,1,0,0,0,0,0,0,0,0,0
7,77888,H. Seferović,ST,RCF,CDM,RW,LW,NaN,12,225,...,0,0,0,0,0,0,0,0,0,0
8,21022,L. Abraham,LCB,NaN,NaN,NaN,NaN,NaN,13,555,...,5,0,0,0,0,0,0,0,1,0
9,8570,L. Hradecky,GK,NaN,NaN,NaN,NaN,NaN,14,323,...,2,0,2,5,0,0,4,0,0,1
10,44079,S. Reinartz,LDM,LCM,NaN,NaN,NaN,NaN,2,120,...,0,0,0,0,0,0,0,0,0,0
11,5335,M. Hasebe,RB,CDM,RWB,LB,RCM,LCM,13,513,...,1,0,0,0,0,0,0,0,0,0
12,16520,S. Aigner,RW,NaN,NaN,NaN,NaN,NaN,12,243,...,0,0,0,0,0,0,0,0,0,0
13,1790,M. Russ,RCM,CM,RCB,LCB,RDM,NaN,10,329,...,3,0,0,0,0,0,0,0,0,0
14,203576,M. Gačinović,LW,RW,RB,NaN,NaN,NaN,5,58,...,0,0,0,0,0,0,0,0,0,0
15,196661,A. Ignjovski,LW,RB,RCM,RW,CAM,NaN,7,132,...,0,0,0,0,0,0,0,0,0,0
16,12956,C. Djakpa,LB,LW,NaN,NaN,NaN,NaN,2,17,...,0,0,0,0,0,0,0,0,0,0
17,102895,L. Castaignos,ST,NaN,NaN,NaN,NaN,NaN,2,3,...,0,0,0,0,0,0,0,0,0,0
18,39442,C. Zambrano,RCB,NaN,NaN,NaN,NaN,NaN,11,447,...,4,0,0,0,0,0,0,0,0,0
19,205986,D. Kinsombi,RW,RCB,NaN,NaN,NaN,NaN,2,20,...,0,0,0,0,0,0,0,0,0,0
20,67519,V. Kadlec,RDM,RB,LW,NaN,NaN,NaN,3,9,...,0,0,0,0,0,0,0,0,0,0
21,201624,K. Ayhan,LCB,NaN,NaN,NaN,NaN,NaN,1,22,...,1,0,0,0,0,0,0,0,0,0
22,57720,T. Chandler,ST,RW,NaN,NaN,NaN,NaN,2,41,...,1,0,0,0,0,0,0,0,0,0
23,206102,J. Gerezgiher,LW,NaN,NaN,NaN,NaN,NaN,1,3,...,0,0,0,0,0,0,0,0,0,0
24,214449,N. Rinderknecht,LCB,NaN,NaN,NaN,NaN,NaN,1,2,...,0,0,0,0,0,0,0,0,0,0
25,143853,S. Kittel,LCM,LW,NaN,NaN,NaN,NaN,3,12,...,0,0,0,0,0,0,0,0,0,0
26,40700,S. Medojević,RCM,LCM,RCB,RDM,RW,NaN,8,132,...,1,0,0,0,0,0,0,0,0,0
27,7466,A. Ben-Hatira,LCB,LCM,NaN,NaN,NaN,NaN,2,26,...,0,0,0,0,0,0,0,0,0,0

In [25]:
dframe_ef.to_csv("ef_overall_stats.csv")