In [3]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [7]:
dframe = pd.read_csv('mozgalo_gladbach_eintracht_csv.csv',sep=";")

In [8]:
dframe

,ID,gameID,actionStartTime,actionEndTime,actionID,bindedActionID,actionOptionID,playerID,touchNumber,playerTeam,...,endPossTime,gameTimeSection,playerPositionID,targetPositionID,awayTeamSide,videoStartTime,videoEndTime,parentID,VideoActionStart,VideoActionEnd
0,6256994,6258,0.00,0.75,247,0,0,21913,1,home,...,0.14,FirstHalf,17,18,left,420.15,420.90,NaN,NaN,NaN
1,6256995,6258,0.75,1.31,247,0,0,1992,1,home,...,1.07,FirstHalf,18,15,left,420.90,421.46,NaN,NaN,NaN
2,6256996,6258,1.31,4.37,247,0,0,1892,2,home,...,2.07,FirstHalf,15,14,left,421.46,424.59,NaN,NaN,NaN
3,6256997,6258,4.37,7.12,247,0,0,201366,2,home,...,5.68,FirstHalf,14,13,left,424.59,427.27,NaN,NaN,NaN
4,6256998,6258,7.12,9.80,247,0,0,114354,1,home,...,7.39,FirstHalf,13,15,left,427.27,430.06,NaN,NaN,NaN
5,6256999,6258,9.80,11.38,247,0,0,1892,2,home,...,10.99,FirstHalf,15,16,left,430.06,431.53,NaN,NaN,NaN
6,6257000,6258,11.38,12.18,247,0,0,38433,1,home,...,11.47,FirstHalf,16,15,left,431.53,432.33,NaN,NaN,NaN
7,6257001,6258,12.18,15.11,247,0,0,1892,2,home,...,13.71,FirstHalf,15,21,left,432.33,435.26,NaN,NaN,NaN
8,6257002,6258,15.11,16.00,247,0,0,102537,1,home,...,15.33,FirstHalf,21,14,left,435.26,436.15,NaN,NaN,NaN
9,6257003,6258,16.00,16.92,247,0,0,201366,1,home,...,16.37,FirstHalf,14,15,left,436.15,437.07,NaN,NaN,NaN
10,6257004,6258,16.92,21.39,247,0,0,1892,4,home,...,19.45,FirstHalf,15,13,left,437.07,441.54,NaN,NaN,NaN
11,6257005,6258,21.39,23.45,247,0,0,114354,2,home,...,22.69,FirstHalf,13,15,left,441.54,443.60,NaN,NaN,NaN
12,6257006,6258,23.45,30.66,247,0,0,1892,7,home,...,29.34,FirstHalf,15,14,left,443.60,450.81,NaN,NaN,NaN
13,6257007,6258,30.66,34.74,247,0,0,201366,5,home,...,34.03,FirstHalf,14,15,left,450.81,454.89,NaN,NaN,NaN
14,6257008,6258,34.74,37.54,247,0,0,1892,4,home,...,36.81,FirstHalf,15,16,left,454.89,457.69,NaN,NaN,NaN
15,6257009,6258,37.54,38.76,247,0,0,38433,1,home,...,37.76,FirstHalf,16,15,left,457.69,458.95,NaN,NaN,NaN
16,6257010,6258,38.76,41.47,247,0,0,1892,3,home,...,40.57,FirstHalf,15,21,left,458.95,461.62,NaN,NaN,NaN
17,6257011,6258,41.47,42.60,22,0,157,102537,1,home,...,41.71,FirstHalf,21,2,left,461.62,462.75,NaN,NaN,NaN
18,6257012,6258,56.97,57.22,247,0,0,38433,1,home,...,57.22,FirstHalf,16,17,left,478.12,478.37,NaN,NaN,NaN
19,6257013,6258,56.97,57.22,261,247,171,38433,1,home,...,57.22,FirstHalf,16,17,left,478.12,478.37,NaN,NaN,NaN
20,6257014,6258,57.22,58.52,247,0,0,21913,1,home,...,57.52,FirstHalf,17,4,left,478.37,479.67,NaN,NaN,NaN
21,6257015,6258,58.52,60.40,247,0,0,79430,1,home,...,58.85,FirstHalf,4,16,left,479.67,481.55,NaN,NaN,NaN
22,6257016,6258,60.40,61.28,247,0,0,38433,1,home,...,60.73,FirstHalf,16,15,left,481.55,482.43,NaN,NaN,NaN
23,6257017,6258,61.28,62.90,247,0,0,1892,1,home,...,61.60,FirstHalf,15,14,left,482.43,484.05,NaN,NaN,NaN
24,6257018,6258,62.90,65.99,247,0,0,201366,2,home,...,64.13,FirstHalf,14,15,left,484.05,487.19,NaN,NaN,NaN
25,6257019,6258,65.99,67.82,247,0,0,1892,2,home,...,67.10,FirstHalf,15,16,left,487.19,488.97,NaN,NaN,NaN
26,6257020,6258,67.82,68.67,247,0,0,38433,1,home,...,68.10,FirstHalf,16,15,left,488.97,489.82,NaN,NaN,NaN
27,6257021,6258,68.67,72.58,247,0,0,1892,5,home,...,72.21,FirstHalf,15,16,left,489.82,493.73,NaN,NaN,NaN
28,6257022,6258,72.58,74.97,247,0,0,38433,2,home,...,73.25,FirstHalf,16,14,left,493.73,496.22,NaN,NaN,NaN
29,6257023,6258,74.97,78.66,247,0,0,201366,4,home,...,77.39,FirstHalf,14,4,left,496.22,499.87,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70301,6896131,6770,5495.62,5497.00,211,13,13,35785,1,away,...,5495.79,SecondHalf,2,0,right,7018.88,7020.26,NaN,NaN,NaN
70302,6896135,6770,5513.17,5514.53,247,0,0,22870,1,home,...,5513.35,SecondHalf,17,13,right,7036.43,7037.79,NaN,NaN,NaN
70303,6896138,6770,5513.17,5514.53,260,247,4,22870,1,home,...,5513.35,SecondHalf,17,13,right,7036.43,7037.79,NaN,NaN,NaN
70304,6896139,6770,5514.53,5514.53,7,0,341,21022,1,home,...,5514.53,SecondHalf,13,4,right,7037.79,7037.79,NaN,NaN,NaN
70305,6896141,6770,5514.53,5515.19,262,0,0,21022,1,home,...,5514.70,SecondHalf,13,0,right,7037.79,7038.45,NaN,NaN,NaN
70306,6896142,6770,5514.53,5515.19,30,262,140,21022,1,home,...,5514.70,SecondHalf,13,0,right,7037.79,7038.45,NaN,NaN,NaN
70307,6896144,6770,5514.53,5515.19,30,262,72,21022,1,home,...,5514.70,SecondHalf,13,0,right,7037.79,7038.45,NaN,NaN,NaN
70308,6896146,6770,5514.53,5515.19,218,262,262,21022,1,home,...,5514.70,SecondHalf,13,0,right,7037.79,7038.45,NaN,NaN,NaN
70309,6896147,6770,5514.53,5515.19,23,262,82,21022,1,home,...,5514.70,SecondHalf,13,0,right,7037.79,7038.45,NaN,NaN,NaN
70310,6896151,6770,5538.13,5542.07,248,0,0,11043,1,away,...,5538.30,SecondHalf,1,5,right,7061.39,7065.33,NaN,NaN,NaN
70311,6896152,6770,5538.13,5542.07,15,248,248,11043,1,away,...,5538.30,SecondHalf,1,5,right,7061.39,7065.33,NaN,NaN,NaN
70312,6896153,6770,5538.13,5542.07,79,248,248,11043,1,away,...,5538.30,SecondHalf,1,5,right,7061.39,7065.33,NaN,NaN,NaN
70313,6896154,6770,5542.07,5542.08,7,0,341,1790,1,home,...,5542.08,SecondHalf,5,11,right,7065.33,7065.34,NaN,NaN,NaN
70314,6896155,6770,5542.08,5543.77,248,0,0,1790,1,home,...,5542.24,SecondHalf,5,15,right,7065.34,7067.03,NaN,NaN,NaN
70315,6896156,6770,5542.08,5543.77,218,248,248,1790,1,home,...,5542.24,SecondHalf,5,15,right,7065.34,7067.03,NaN,NaN,NaN
70316,6896157,6770,5543.77,5546.90,232,0,250,9795,1,away,...,5543.96,SecondHalf,15,0,right,7067.03,7070.16,NaN,NaN,NaN
70317,6896158,6770,5543.77,5546.90,15,232,232,9795,1,away,...,5543.96,SecondHalf,15,0,right,7067.03,7070.16,NaN,NaN,NaN
70318,6896162,6770,5551.56,5553.69,247,0,0,212914,1,home,...,5551.73,SecondHalf,23,18,right,7074.82,7076.95,NaN,NaN,NaN
70319,6896163,6770,5551.56,5553.69,211,247,247,212914,1,home,...,5551.73,SecondHalf,23,18,right,7074.82,7076.95,NaN,NaN,NaN
70320,6896166,6770,5553.69,5555.43,247,0,0,77888,1,home,...,5554.28,SecondHalf,18,17,right,7076.95,7078.69,NaN,NaN,NaN
70321,6896169,6770,5555.43,5556.33,22,0,157,22870,2,home,...,5556.33,SecondHalf,17,8,right,7078.69,7079.59,NaN,NaN,NaN
70322,6896173,6770,5555.43,5556.33,10,22,210,22870,0,home,...,5556.33,SecondHalf,17,8,right,7078.69,7079.59,NaN,NaN,NaN
70323,6896179,6770,5604.66,5606.07,247,0,0,22870,1,home,...,5604.84,SecondHalf,17,23,right,7127.92,7129.33,NaN,NaN,NaN
70324,6896181,6770,5604.66,5606.07,261,247,171,22870,1,home,...,5604.84,SecondHalf,17,23,right,7127.92,7129.33,NaN,NaN,NaN
70325,6896188,6770,5606.07,5610.15,248,0,0,212914,5,home,...,5608.88,SecondHalf,23,13,right,7129.33,7133.41,NaN,NaN,NaN
70326,6896189,6770,5606.07,5610.15,15,248,248,212914,5,home,...,5608.88,SecondHalf,23,13,right,7129.33,7133.41,NaN,NaN,NaN
70327,6896192,6770,5610.15,5614.10,232,0,250,54689,1,away,...,5610.34,SecondHalf,13,0,right,7133.41,7137.36,NaN,NaN,NaN
70328,6896193,6770,5610.15,5614.10,218,232,232,54689,1,away,...,5610.34,SecondHalf,13,0,right,7133.41,7137.36,NaN,NaN,NaN
70329,6896196,6770,5610.15,5614.10,17,232,301,54689,1,away,...,5610.34,SecondHalf,13,0,right,7133.41,7137.36,NaN,NaN,NaN
70330,6896197,6770,5610.15,5614.10,211,232,232,54689,1,away,...,5610.34,SecondHalf,13,0,right,7133.41,7137.36,NaN,NaN,NaN

In [9]:
dframe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 70331 entries, 0 to 70330
Data columns (total 35 columns):
ID                  70331 non-null int64
gameID              70331 non-null int64
actionStartTime     70331 non-null float64
actionEndTime       70331 non-null float64
actionID            70331 non-null int64
bindedActionID      70331 non-null int64
actionOptionID      70331 non-null int64
playerID            70331 non-null int64
touchNumber         70331 non-null int64
playerTeam          70331 non-null object
actionPosX1         70331 non-null float64
actionPosX2         70331 non-null float64
actionPosY1         70331 non-null float64
actionPosY2         70331 non-null float64
targetPlayerID      70331 non-null int64
goalZone            5201 non-null object
lineColor           67099 non-null object
lineDirection       67099 non-null object
distance            70331 non-null float64
refPositionX        70331 non-null float64
refPositionY        70331 non-null float64
datum               70331 non-null object
ref                 0 non-null float64
coach               0 non-null float64
startPossTime       70331 non-null float64
endPossTime         70331 non-null float64
gameTimeSection     70331 non-null object
playerPositionID    70331 non-null int64
targetPositionID    70331 non-null int64
awayTeamSide        70331 non-null object
videoStartTime      70331 non-null float64
videoEndTime        70331 non-null float64
parentID            0 non-null float64
VideoActionStart    0 non-null float64
VideoActionEnd      0 non-null float64
dtypes: float64(18), int64(10), object(7)
memory usage: 19.3+ MB

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [36]:
#
gameIDs = pd.unique(dframe['gameID'])

In [38]:
gameIDs

array([6258, 6261, 6307, 6308, 6347, 6364, 6370, 6385, 6398, 6403, 6418,
       6425, 6450, 6462, 6545, 6553, 6568, 6573, 6603, 6609, 6647, 6652,
       6681, 6685, 6725, 6730, 6755, 6756, 6765, 6770])

In [37]:
gameIDs.size

30

In [20]:
playerIDs = pd.unique(dframe['playerID'])

In [39]:
playerIDs

array([ 21913,   1992,   1892, 201366, 114354,  38433, 102537,  79430,
        54482,  44079, 199745,  89661, 196633,  21022, 196661,   5335,
        16520,  77888,   1802, 198668,  39442,   8570,  16894,  11500,
        66692,  35785,  84297,  78198, 206309,  96310,  16271,  16491,
        39479,  54769,   1818, 102647,   4610, 205485,  16087,  37911,
        11043,  11341,  68597,  54689,   1819, 204427,  62146, 102895,
       115078, 205986,  63129, 167977, 156709, 205180, 201539,  59326,
        53084, 167694, 126631,  65256,  89662,   9354, 201879, 138853,
        73607,  73299,   2025,  54180, 171186,  53937,  40700,  44428,
        81305, 198337, 130205, 110657,  79410, 201853,  56958, 102533,
        57720,   1897, 206102, 203641, 206101, 161221,  49374,  32926,
       206094, 200739,  13690,  20356,  58666,   2183,  95786,  65127,
        13122,  68515, 208487, 148852,  13635,  47041,   3153,  32947,
        43159,   7759, 109708, 116414, 203576, 196658,  29434,  54894,
       102535,  39381, 123620, 156937,   6045, 202061, 196781, 175582,
       196096,  67519,  87892,  10432,   5917,  16386,  13730,   1975,
          332,  41310,  38215,     14, 201869,   1970,   4470,  38020,
          547,  54183,  55796,   1775,  57667,   8243,   2454, 120261,
       206155,  95861,  39007,  88465,   1790,  31564,  38466,  17305,
        78532, 199833,  66411,  68177,   2842,   4496,   3026,  17782,
         2956,  53097,  19655,   8835,  59705,   1407,   1938, 207917,
        55626,  37644,  69050,  16890,  16492,  16381,  71993,  39797,
        65860, 204281,  39421,  12956,  25072,  19278,  22397, 214449,
         2054,   2022, 143213, 201849, 175390, 122073,  23179,  38494,
       210557,  85380,  63828, 205472,  16416, 203976,  17663,   1707,
        16901,  39468,   1807,  33327, 197261, 167009, 185121, 127794,
        86503,  38500,  38434,  17015,   1770,  54495, 170341, 206251,
          196,  75357,   2039,  53129,  22870,  63400,  16090,  16504,
        39466, 136144, 158542,  41398,  11554,  78561,  16507,  97317,
         2122, 199175,  39650, 119758, 206190,   2324, 124251,   1693,
        97318,   2003, 113551, 212244, 202521,  11232, 201460,   4613,
       209422, 201624,   1939, 212914,  17326,  55773, 197072, 197680,
        38209,  33894,  58565,  16344,  78485, 202092,   7466,  20947,
        11030, 151771,  44080, 179905,  16475, 201934, 141580,  54414,
       141582, 196657,  13773, 161525,  69056,   1641,  74231, 162898,
        29485,   2034,   5949, 113769, 205987,  57544,  97021,   1882,
        74560,  56968,   1665,  38496,  48626,    200, 153052, 139141,
        74303, 144607, 215487,  54704,  32128,  11891,  32400, 175281,
       101189, 201239,  87814,  16111,  16345,  54779, 163804,  80975,
        16508,   2179, 199097, 101192,  16690, 200732, 206051,  59163,
       143853,   2037,   2540,   1645, 127888, 197255,  35445, 176540,
         7875, 201345,   7910, 102526,  74310, 158568,  11538, 210990,
       150680,  86026, 196650, 196922,  10592, 126639, 201520, 201931,
         9795,  47090,  56086])

In [34]:
playerIDs.size

347

In [58]:
grouped = dframe.groupby(['gameID'])

In [60]:
grouped.size()

gameID
6258    2199
6261    1882
6307    2352
6308    2300
6347    2293
6364    2505
6370    2298
6385    2711
6398    1923
6403    2748
6418    1993
6425    2399
6450    2349
6462    1903
6545    2581
6553    2485
6568    2488
6573    2172
6603    2307
6609    2289
6647    2331
6652    2500
6681    2507
6685    2656
6725    2548
6730    2309
6755    2304
6756    2112
6765    2443
6770    2444
dtype: int64

In [61]:
grouped.describe()

                          ID  VideoActionEnd  VideoActionStart  actionEndTime  \
gameID
6258   count     2199.000000               0                 0    2199.000000
       mean   6260844.303774             NaN               NaN    2613.759059
       std       2581.864043             NaN               NaN    1572.099327
       min    6256994.000000             NaN               NaN       0.750000
       25%    6258422.500000             NaN               NaN    1260.190000
       50%    6260578.000000             NaN               NaN    2585.010000
       75%    6263260.000000             NaN               NaN    4020.425000
       max    6265371.000000             NaN               NaN    5583.590000
6261   count     1882.000000               0                 0    1882.000000
       mean   6263977.023379             NaN               NaN    2686.916153
       std       3715.072288             NaN               NaN    1577.719714
       min    6257304.000000             NaN               NaN       0.200000
       25%    6260877.250000             NaN               NaN    1345.307500
       50%    6264408.500000             NaN               NaN    2725.025000
       75%    6267465.250000             NaN               NaN    4001.550000
       max    6269156.000000             NaN               NaN    5514.260000
6307   count     2352.000000               0                 0    2352.000000
       mean   6310399.613946             NaN               NaN    2722.733176
       std       4082.924283             NaN               NaN    1589.814366
       min    6304183.000000             NaN               NaN      -0.610000
       25%    6306672.500000             NaN               NaN    1349.175000
       50%    6309984.000000             NaN               NaN    2702.090000
       75%    6314351.500000             NaN               NaN    4108.000000
       max    6317207.000000             NaN               NaN    5634.170000
6308   count     2300.000000               0                 0    2300.000000
       mean   6311558.281304             NaN               NaN    2695.163978
       std       3864.874614             NaN               NaN    1637.126059
       min    6305163.000000             NaN               NaN       0.750000
       25%    6308196.750000             NaN               NaN    1361.620000
       50%    6311300.000000             NaN               NaN    2642.430000
...                      ...             ...               ...            ...
6755   std       4329.499014             NaN               NaN    1578.999461
       min    6855710.000000             NaN               NaN      -0.680000
       25%    6859654.500000             NaN               NaN    1200.140000
       50%    6863685.000000             NaN               NaN    2725.945000
       75%    6867670.250000             NaN               NaN    3901.940000
       max    6869827.000000             NaN               NaN    5406.210000
6756   count     2112.000000               0                 0    2112.000000
       mean   6864719.780777             NaN               NaN    2681.438830
       std       3816.854481             NaN               NaN    1588.447334
       min    6857513.000000             NaN               NaN       0.790000
       25%    6861434.250000             NaN               NaN    1286.752500
       50%    6864814.000000             NaN               NaN    2586.795000
       75%    6868340.750000             NaN               NaN    4017.272500
       max    6870230.000000             NaN               NaN    5572.210000
6765   count     2443.000000               0                 0    2443.000000
       mean   6884994.332378             NaN               NaN    2757.392828
       std       3295.984913             NaN               NaN    1623.098494
       min    6880228.000000             NaN               NaN       0.060000
       25%    6881971.500000             NaN               NaN    1354.015000
       50%    6884816.000000             NaN               NaN    2815.620000
       75%    6887841.500000             NaN               NaN    4093.180000
       max    6890792.000000             NaN               NaN    5585.990000
6770   count     2444.000000               0                 0    2444.000000
       mean   6889654.414894             NaN               NaN    2741.030933
       std       4559.341240             NaN               NaN    1611.008246
       min    6881295.000000             NaN               NaN      -0.360000
       25%    6885652.250000             NaN               NaN    1329.585000
       50%    6890215.500000             NaN               NaN    2740.705000
       75%    6893985.750000             NaN               NaN    4118.940000
       max    6896197.000000             NaN               NaN    5614.100000

                 actionID  actionOptionID  actionPosX1  actionPosX2  \
gameID
6258   count  2199.000000     2199.000000  2199.000000  2199.000000
       mean    190.086858       85.411551   662.419736   659.813552
       std     101.098301      117.268415   317.812769   335.927313
       min       2.000000        0.000000     0.000000     0.000000
       25%     116.500000        0.000000   434.000000   419.000000
       50%     247.000000        0.000000   662.000000   656.000000
       75%     247.000000      232.000000   917.500000   913.000000
       max     375.000000      378.000000  1288.000000  1321.000000
6261   count  1882.000000     1882.000000  1882.000000  1882.000000
       mean    183.264612       90.688629   611.672157   602.681190
       std     105.185601      116.485755   310.585236   332.222312
       min       2.000000        0.000000     0.000000     0.000000
       25%      30.000000        0.000000   380.500000   360.000000
       50%     247.000000        0.000000   575.000000   579.000000
       75%     247.000000      232.000000   852.250000   853.000000
       max     375.000000      378.000000  1285.000000  1305.000000
6307   count  2352.000000     2352.000000  2352.000000  2352.000000
       mean    185.781463       99.431548   669.585459   651.497024
       std     104.083278      124.745551   337.790356   359.503241
       min       1.000000        0.000000     0.000000     0.000000
       25%      31.000000        0.000000   406.000000   390.000000
       50%     247.000000        0.000000   660.000000   644.500000
       75%     247.000000      247.000000   929.000000   918.250000
       max     375.000000      378.000000  1287.000000  1328.000000
6308   count  2300.000000     2300.000000  2300.000000  2300.000000
       mean    163.876957      128.425217   671.366087   655.749565
       std     113.381272      126.882749   339.089662   366.475093
       min       1.000000        0.000000     0.000000     0.000000
       25%      18.000000        0.000000   421.000000   365.000000
       50%     218.000000      104.000000   643.000000   640.500000
...                   ...             ...          ...          ...
6755   std     104.212062      126.999291   334.378865   359.458834
       min       1.000000        0.000000     0.000000     0.000000
       25%      65.000000        0.000000   433.500000   397.000000
       50%     247.000000        0.000000   697.000000   675.500000
       75%     247.000000      247.000000   978.000000   965.250000
       max     375.000000      378.000000  1289.000000  1323.000000
6756   count  2112.000000     2112.000000  2112.000000  2112.000000
       mean    201.676136      106.775095   661.286458   645.339962
       std      92.084149      127.902253   301.738944   335.978510
       min       1.000000        0.000000     0.000000     0.000000
       25%     211.000000        0.000000   429.000000   412.500000
       50%     247.000000        0.000000   654.500000   648.000000
       75%     247.000000      247.000000   885.500000   875.250000
       max     375.000000      378.000000  1290.000000  1332.000000
6765   count  2443.000000     2443.000000  2443.000000  2443.000000
       mean    187.914040       93.904625   644.155546   630.576341
       std     101.019265      120.597843   308.888916   329.930879
       min       1.000000        0.000000     0.000000     0.000000
       25%      79.000000        0.000000   406.000000   387.000000
       50%     247.000000        0.000000   620.000000   617.000000
       75%     247.000000      247.000000   884.000000   872.000000
       max     375.000000      378.000000  1285.000000  1316.000000
6770   count  2444.000000     2444.000000  2444.000000  2444.000000
       mean    169.755319      129.796645   725.469313   686.254501
       std     108.716886      128.499142   336.178790   372.841586
       min       1.000000        0.000000     0.000000     0.000000
       25%      23.000000        0.000000   451.000000   403.000000
       50%     218.000000      104.000000   732.500000   704.000000
       75%     247.000000      248.000000  1012.000000   989.000000
       max     375.000000      378.000000  1284.000000  1316.000000

              actionPosY1  actionPosY2       ...        playerPositionID  ref  \
gameID                                       ...
6258   count  2199.000000  2199.000000       ...             2199.000000    0
       mean    419.966385   412.315489       ...               11.925421  NaN
       std     215.327321   217.984129       ...                6.410714  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     251.320000   251.820000       ...                4.000000  NaN
       50%     428.320000   421.320000       ...               14.000000  NaN
       75%     592.320000   585.320000       ...               16.000000  NaN
       max     836.320000   828.320000       ...               21.000000  NaN
6261   count  1882.000000  1882.000000       ...             1882.000000    0
       mean    448.350329   439.874198       ...               11.438363  NaN
       std     224.467456   225.129443       ...                6.633464  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     251.570000   244.820000       ...                4.000000  NaN
       50%     473.320000   456.320000       ...               13.000000  NaN
       75%     634.070000   626.070000       ...               16.000000  NaN
       max     800.320000   844.320000       ...               21.000000  NaN
6307   count  2352.000000  2352.000000       ...             2352.000000    0
       mean    441.790697   428.380578       ...               11.898384  NaN
       std     214.123306   218.699463       ...                6.761499  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     268.570000   257.320000       ...                4.000000  NaN
       50%     461.320000   436.320000       ...               14.000000  NaN
       75%     624.320000   610.320000       ...               17.000000  NaN
       max     804.320000   828.320000       ...               21.000000  NaN
6308   count  2300.000000  2300.000000       ...             2300.000000    0
       mean    402.216417   394.525704       ...               11.160435  NaN
       std     221.370294   221.089365       ...                6.403423  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     205.320000   203.070000       ...                4.000000  NaN
       50%     393.820000   399.320000       ...               13.000000  NaN
...                   ...          ...       ...                     ...  ...
6755   std     223.228890   233.662804       ...                7.568399  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     250.070000   231.320000       ...                9.000000  NaN
       50%     447.320000   433.320000       ...               14.000000  NaN
       75%     636.320000   631.320000       ...               20.000000  NaN
       max     799.320000   845.320000       ...               27.000000  NaN
6756   count  2112.000000  2112.000000       ...             2112.000000    0
       mean    421.901629   413.385606       ...               11.925189  NaN
       std     209.101123   212.580236       ...                7.532408  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     255.070000   246.320000       ...                4.000000  NaN
       50%     423.820000   419.320000       ...               14.000000  NaN
       75%     582.320000   570.570000       ...               17.000000  NaN
       max     815.320000   828.320000       ...               27.000000  NaN
6765   count  2443.000000  2443.000000       ...             2443.000000    0
       mean    380.842341   376.453000       ...               13.632419  NaN
       std     214.225446   215.213891       ...                6.364441  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     192.320000   186.820000       ...                9.000000  NaN
       50%     378.320000   382.320000       ...               15.000000  NaN
       75%     556.820000   547.320000       ...               18.000000  NaN
       max     808.320000   814.320000       ...               23.000000  NaN
6770   count  2444.000000  2444.000000       ...             2444.000000    0
       mean    418.901997   399.194239       ...               12.015139  NaN
       std     220.924093   235.640555       ...                6.903416  NaN
       min       0.000000     0.000000       ...                1.000000  NaN
       25%     229.320000   202.320000       ...                5.000000  NaN
       50%     419.320000   406.320000       ...               13.000000  NaN
       75%     601.320000   592.320000       ...               17.000000  NaN
       max     799.320000   838.320000       ...               23.000000  NaN

              refPositionX  refPositionY  startPossTime  targetPlayerID  \
gameID
6258   count   2199.000000   2199.000000    2199.000000     2199.000000
       mean      11.892224      7.331733    2600.679341    69821.396089
       std       93.288128     56.003634    1573.540081    77091.576934
       min        0.000000      0.000000       0.000000        0.000000
       25%        0.000000      0.000000    1254.890000     1992.000000
       50%        0.000000      0.000000    2580.820000    39442.000000
       75%        0.000000      0.000000    4018.210000   114354.000000
       max     1042.000000    596.320000    5576.060000   204427.000000
6261   count   1882.000000   1882.000000    1882.000000     1882.000000
       mean      16.930925     11.617067    2670.100962    52136.822529
       std      105.950123     71.563264    1581.030616    53019.296459
       min        0.000000      0.000000       0.000000        0.000000
       25%        0.000000      0.000000    1327.960000    11341.000000
       50%        0.000000      0.000000    2711.555000    39479.000000
       75%        0.000000      0.000000    3996.472500    78198.000000
       max      928.000000    725.320000    5513.240000   206309.000000
6307   count   2352.000000   2352.000000    2352.000000     2352.000000
       mean       9.674745      5.512296    2707.302037    67710.685374
       std       87.895036     49.513700    1591.261319    70869.835220
       min        0.000000      0.000000      -0.750000        0.000000
       25%        0.000000      0.000000    1341.460000     9354.000000
       50%        0.000000      0.000000    2697.770000    53084.000000
       75%        0.000000      0.000000    4073.500000   126631.000000
       max     1072.000000    605.320000    5633.180000   206309.000000
6308   count   2300.000000   2300.000000    2300.000000     2300.000000
       mean      12.345652      8.223217    2682.345061    82609.002609
       std       91.643266     60.498753    1640.371593    73280.862585
       min        0.000000      0.000000       0.000000        0.000000
       25%        0.000000      0.000000    1345.627500    16520.000000
       50%        0.000000      0.000000    2627.830000    57720.000000
...                    ...           ...            ...             ...
6755   std       64.853984     47.610632    1583.416430    78920.427507
       min        0.000000      0.000000      -0.830000        0.000000
       25%        0.000000      0.000000    1184.390000    11500.000000
       50%        0.000000      0.000000    2720.350000    38209.000000
       75%        0.000000      0.000000    3893.860000   156709.000000
       max      949.000000    614.320000    5405.100000   206309.000000
6756   count   2112.000000   2112.000000    2112.000000     2112.000000
       mean      12.955966      8.809242    2667.703509    65137.909091
       std       94.239032     63.855519    1590.706452    77352.664338
       min        0.000000      0.000000       0.000000        0.000000
       25%        0.000000      0.000000    1273.270000     2540.000000
       50%        0.000000      0.000000    2563.350000    21022.000000
       75%        0.000000      0.000000    4006.160000   127888.000000
       max      956.000000    591.320000    5571.390000   210990.000000
6765   count   2443.000000   2443.000000    2443.000000     2443.000000
       mean      10.366353      5.828686    2744.293381    90082.028653
       std       83.427501     47.155904    1626.741035    74450.604891
       min        0.000000      0.000000      -0.050000        0.000000
       25%        0.000000      0.000000    1349.350000    16087.000000
       50%        0.000000      0.000000    2797.880000    75357.000000
       75%        0.000000      0.000000    4088.505000   156709.000000
       max      941.000000    554.320000    5584.630000   206309.000000
6770   count   2444.000000   2444.000000    2444.000000     2444.000000
       mean      14.650164      9.518658    2731.157361    64281.687807
       std      102.946079     66.435793    1615.056662    75979.723637
       min        0.000000      0.000000      -0.510000        0.000000
       25%        0.000000      0.000000    1311.310000     5335.000000
       50%        0.000000      0.000000    2730.790000    35785.000000
       75%        0.000000      0.000000    4115.560000    78198.000000
       max     1062.000000    653.320000    5610.150000   212914.000000

              targetPositionID  touchNumber  videoEndTime  videoStartTime
gameID
6258   count       2199.000000  2199.000000   2199.000000     2199.000000
       mean          10.854479     1.922692   3519.549281     3516.938777
       std            7.039258     1.453692   2031.805295     2031.666991
       min            0.000000     0.000000    420.900000      420.150000
       25%            2.000000     1.000000   1681.340000     1678.140000
       50%           14.000000     2.000000   3006.160000     3005.360000
       75%           16.000000     2.000000   5463.340000     5462.630000
       max           21.000000     8.000000   7026.510000     7019.050000
6261   count       1882.000000  1882.000000   1882.000000     1882.000000
       mean          10.817747     1.662062   3686.335558     3683.837418
       std            7.237392     1.296761   2017.456738     2017.509334
       min            0.000000     0.000000    502.500000      502.300000
       25%            2.000000     1.000000   1847.617500     1845.120000
       50%           13.000000     1.000000   4205.955000     4201.695000
       75%           16.000000     2.000000   5482.480000     5479.967500
       max           21.000000     8.000000   6995.220000     6994.170000
6307   count       2352.000000  2352.000000   2352.000000     2352.000000
       mean          10.798469     2.011480   3153.986569     3151.497066
       std            7.301913     1.642260   1636.522521     1636.624332
       min            0.000000     0.000000    376.800000      376.650000

In [62]:
groupedpID = dframe.groupby(['gameID','playerID'])

In [63]:
groupedpID.describe()

                                   ID  VideoActionEnd  VideoActionStart  \
gameID playerID
6258   1802     count       63.000000               0                 0
                mean   6260332.793651             NaN               NaN
                std       2488.593794             NaN               NaN
                min    6257082.000000             NaN               NaN
                25%    6257560.500000             NaN               NaN
                50%    6260082.000000             NaN               NaN
                75%    6262689.000000             NaN               NaN
                max    6265165.000000             NaN               NaN
       1819     count       60.000000               0                 0
                mean   6263757.766667             NaN               NaN
                std        810.858017             NaN               NaN
                min    6262495.000000             NaN               NaN
                25%    6263026.250000             NaN               NaN
                50%    6263846.000000             NaN               NaN
                75%    6264451.500000             NaN               NaN
                max    6265203.000000             NaN               NaN
       1892     count      149.000000               0                 0
                mean   6260636.946309             NaN               NaN
                std       2617.823835             NaN               NaN
                min    6256996.000000             NaN               NaN
                25%    6258060.000000             NaN               NaN
                50%    6260522.000000             NaN               NaN
                75%    6263137.000000             NaN               NaN
                max    6265191.000000             NaN               NaN
       1992     count       63.000000               0                 0
                mean   6259621.809524             NaN               NaN
                std       2049.193806             NaN               NaN
                min    6256995.000000             NaN               NaN
                25%    6258233.000000             NaN               NaN
                50%    6258621.000000             NaN               NaN
...                               ...             ...               ...
6770   201539   std       2621.997269             NaN               NaN
                min    6881395.000000             NaN               NaN
                25%    6884126.000000             NaN               NaN
                50%    6886420.000000             NaN               NaN
                75%    6888033.000000             NaN               NaN
                max    6891599.000000             NaN               NaN
       201931   count       46.000000               0                 0
                mean   6889454.413043             NaN               NaN
                std       4275.393407             NaN               NaN
                min    6882319.000000             NaN               NaN
                25%    6887371.500000             NaN               NaN
                50%    6887792.500000             NaN               NaN
                75%    6894001.500000             NaN               NaN
                max    6895871.000000             NaN               NaN
       206101   count       59.000000               0                 0
                mean   6892822.813559             NaN               NaN
                std       1901.704820             NaN               NaN
                min    6889840.000000             NaN               NaN
                25%    6891039.000000             NaN               NaN
                50%    6892880.000000             NaN               NaN
                75%    6894403.500000             NaN               NaN
                max    6895885.000000             NaN               NaN
       212914   count      128.000000               0                 0
                mean   6889309.445312             NaN               NaN
                std       4845.706665             NaN               NaN
                min    6881481.000000             NaN               NaN
                25%    6885315.250000             NaN               NaN
                50%    6888912.500000             NaN               NaN
                75%    6894396.250000             NaN               NaN
                max    6896189.000000             NaN               NaN

                       actionEndTime    actionID  actionOptionID  actionPosX1  \
gameID playerID
6258   1802     count      63.000000   63.000000       63.000000    63.000000
                mean     2301.174762  148.936508      101.190476   830.619048
                std      1514.423198  116.170741      115.412843   293.608112
                min       250.520000    2.000000        0.000000    62.000000
                25%       692.210000   30.000000        0.000000   595.000000
                50%      2090.060000  218.000000       72.000000   847.000000
                75%      3709.300000  247.000000      176.000000  1100.000000
                max      5412.720000  371.000000      373.000000  1230.000000
       1819     count      60.000000   60.000000       60.000000    60.000000
                mean     4391.970167  205.533333       58.283333   634.283333
                std       544.644806   90.290579      102.937877   206.594427
                min      3555.300000    4.000000        0.000000     0.000000
                25%      3852.322500  228.500000        0.000000   524.000000
                50%      4427.200000  247.000000        0.000000   625.000000
                75%      4869.610000  247.000000      104.000000   781.000000
                max      5436.200000  371.000000      373.000000   961.000000
       1892     count     149.000000  149.000000      149.000000   149.000000
                mean     2471.304899  220.583893       33.926174   708.973154
                std      1608.710714   71.361385       80.480575   208.038391
                min         4.370000   10.000000        0.000000   291.000000
                25%      1055.950000  247.000000        0.000000   529.000000
                50%      2542.030000  247.000000        0.000000   753.000000
                75%      3928.620000  247.000000        0.000000   846.000000
                max      5427.680000  261.000000      285.000000  1238.000000
       1992     count      63.000000   63.000000       63.000000    63.000000
                mean     1892.558889  183.666667      128.968254   552.317460
                std      1209.380073  118.909019      140.811126   294.144897
                min         1.310000    6.000000        0.000000    95.000000
                25%      1166.640000   30.000000        0.000000   387.000000
                50%      1347.600000  247.000000      102.000000   564.000000
...                              ...         ...             ...          ...
6770   201539   std       829.423288  103.252373      135.882949   261.938618
                min        10.510000    4.000000        0.000000   176.000000
                25%       811.800000  211.000000        0.000000   438.000000
                50%      1582.490000  232.000000      210.000000   593.000000
                75%      2148.050000  247.000000      250.000000   731.000000
                max      3165.410000  371.000000      374.000000  1276.000000
       201931   count      46.000000   46.000000       46.000000    46.000000
                mean     2698.839783  155.521739      113.826087   877.586957
                std      1570.457626  120.153002      136.031909   295.560377
                min       302.490000    3.000000        0.000000   268.000000
                25%      1925.570000   24.750000        0.000000   638.500000
                50%      2032.195000  218.000000       38.000000   959.500000
                75%      4162.270000  247.000000      247.750000  1128.000000
                max      5291.820000  371.000000      373.000000  1235.000000
       206101   count      59.000000   59.000000       59.000000    59.000000
                mean     3726.039661  184.694915      120.881356   940.728814
                std       815.626230  119.103874      135.448181   239.459797
                min      2700.000000    4.000000        0.000000     0.000000
                25%      2980.255000   30.000000        0.000000   811.000000
                50%      3628.810000  247.000000      101.000000  1027.000000
                75%      4323.590000  248.000000      247.000000  1091.000000
                max      5300.320000  371.000000      374.000000  1236.000000
       212914   count     128.000000  128.000000      128.000000   128.000000
                mean     2638.586953  194.851562      109.937500   708.976562
                std      1728.506895   89.744966      120.847972   320.688395
                min        47.680000    2.000000        0.000000   154.000000
                25%      1223.680000  211.000000        0.000000   441.500000
                50%      2468.180000  247.000000        0.000000   708.000000
                75%      4322.740000  247.000000      247.000000   972.000000
                max      5610.150000  371.000000      372.000000  1251.000000

                       actionPosX2  actionPosY1  actionPosY2       ...        \
gameID playerID                                                    ...
6258   1802     count    63.000000    63.000000    63.000000       ...
                mean    838.555556   479.367619   459.690794       ...
                std     408.048534   146.828453   190.434692       ...
                min       0.000000   187.320000     0.000000       ...
                25%     553.000000   372.320000   375.320000       ...
                50%     897.000000   449.320000   426.320000       ...
                75%    1236.000000   554.320000   663.320000       ...
                max    1276.000000   770.320000   819.320000       ...
       1819     count    60.000000    60.000000    60.000000       ...
                mean    711.916667   420.131333   451.064667       ...
                std     302.800225   159.388225   215.937602       ...
                min       0.000000     0.000000     0.000000       ...
                25%     526.500000   302.320000   316.820000       ...
                50%     681.500000   434.320000   464.320000       ...
                75%     897.000000   522.070000   613.070000       ...
                max    1312.000000   742.320000   805.320000       ...
       1892     count   149.000000   149.000000   149.000000       ...
                mean    687.859060   417.534765   394.474362       ...
                std     199.980844   116.453248   198.731101       ...
                min     203.000000   167.320000    34.320000       ...
                25%     537.000000   333.320000   243.320000       ...
                50%     709.000000   417.320000   407.320000       ...
                75%     832.000000   498.320000   528.320000       ...
                max    1164.000000   775.320000   766.320000       ...
       1992     count    63.000000    63.000000    63.000000       ...
                mean    554.222222   414.764444   390.103492       ...
                std     334.587297   183.269657   218.589151       ...
                min       0.000000    80.320000     0.000000       ...
                25%     269.000000   283.320000   253.320000       ...
                50%     598.000000   444.320000   364.320000       ...
...                            ...          ...          ...       ...
6770   201539   std     289.415184   207.897253   256.489870       ...
                min       0.000000    56.320000     0.000000       ...
                25%     539.000000   144.320000    95.320000       ...
                50%     640.000000   232.320000   302.320000       ...
                75%     836.000000   497.320000   565.320000       ...
                max    1312.000000   758.320000   815.320000       ...
       201931   count    46.000000    46.000000    46.000000       ...
                mean    848.217391   402.906957   355.733913       ...
                std     392.097489   168.235493   199.177309       ...
                min       0.000000    81.320000     0.000000       ...
                25%     518.250000   305.070000   221.570000       ...
                50%     937.500000   399.320000   373.820000       ...
                75%    1161.000000   541.320000   503.570000       ...
                max    1303.000000   707.320000   722.320000       ...
       206101   count    59.000000    59.000000    59.000000       ...
                mean    920.169492   325.704407   336.744407       ...
                std     321.210864   177.675527   177.107740       ...
                min       0.000000     0.000000     0.000000       ...
                25%     764.500000   200.320000   209.320000       ...
                50%    1009.000000   326.320000   325.320000       ...
                75%    1153.000000   432.320000   476.320000       ...
                max    1307.000000   730.320000   728.320000       ...
       212914   count   128.000000   128.000000   128.000000       ...
                mean    716.710938   392.460625   385.104062       ...
                std     397.440139   303.559454   240.048552       ...
                min       0.000000    45.320000     0.000000       ...
                25%     383.000000    93.320000   193.320000       ...
                50%     668.000000   251.320000   307.820000       ...
                75%    1136.000000   713.570000   620.320000       ...
                max    1249.000000   796.320000   784.320000       ...

                       playerPositionID  ref  refPositionX  refPositionY  \
gameID playerID
6258   1802     count                63    0     63.000000     63.000000
                mean                  9  NaN     32.714286     20.015238
                std                   0  NaN    147.699502     90.243246
                min                   9  NaN      0.000000      0.000000
                25%                   9  NaN      0.000000      0.000000
                50%                   9  NaN      0.000000      0.000000
                75%                   9  NaN      0.000000      0.000000
                max                   9  NaN    713.000000    425.320000
       1819     count                60    0     60.000000     60.000000
                mean                 16  NaN      0.000000      0.000000
                std                   0  NaN      0.000000      0.000000
                min                  16  NaN      0.000000      0.000000
                25%                  16  NaN      0.000000      0.000000
                50%                  16  NaN      0.000000      0.000000
                75%                  16  NaN      0.000000      0.000000
                max                  16  NaN      0.000000      0.000000
       1892     count               149    0    149.000000    149.000000
                mean                 15  NaN     19.798658      9.914631
                std                   0  NaN    122.786454     60.393661
                min                  15  NaN      0.000000      0.000000
                25%                  15  NaN      0.000000      0.000000
                50%                  15  NaN      0.000000      0.000000
                75%                  15  NaN      0.000000      0.000000
                max                  15  NaN    982.000000    425.320000
       1992     count                63    0     63.000000     63.000000
                mean                 18  NaN     19.555556     13.311746
                std                   0  NaN    112.325245     75.165920
                min                  18  NaN      0.000000      0.000000
                25%                  18  NaN      0.000000      0.000000
                50%                  18  NaN      0.000000      0.000000
...                                 ...  ...           ...           ...
6770   201539   std                   0  NaN    163.255434    110.733672
                min                  15  NaN      0.000000      0.000000
                25%                  15  NaN      0.000000      0.000000
                50%                  15  NaN      0.000000      0.000000
                75%                  15  NaN      0.000000      0.000000
                max                  15  NaN    956.000000    617.320000
       201931   count                46    0     46.000000     46.000000
                mean                 20  NaN     15.195652     10.180870
                std                   0  NaN    103.061927     69.050017
                min                  20  NaN      0.000000      0.000000
                25%                  20  NaN      0.000000      0.000000
                50%                  20  NaN      0.000000      0.000000
                75%                  20  NaN      0.000000      0.000000
                max                  20  NaN    699.000000    468.320000
       206101   count                59    0     59.000000     59.000000
                mean                 15  NaN     51.932203     24.394576
                std                   0  NaN    197.353076     96.887253
                min                  15  NaN      0.000000      0.000000
                25%                  15  NaN      0.000000      0.000000
                50%                  15  NaN      0.000000      0.000000
                75%                  15  NaN      0.000000      0.000000
                max                  15  NaN    977.000000    562.320000
       212914   count               128    0    128.000000    128.000000
                mean                 23  NaN      3.570312      3.916562
                std                   0  NaN     40.393475     44.310846
                min                  23  NaN      0.000000      0.000000
                25%                  23  NaN      0.000000      0.000000
                50%                  23  NaN      0.000000      0.000000
                75%                  23  NaN      0.000000      0.000000
                max                  23  NaN    457.000000    501.320000

                       startPossTime  targetPlayerID  targetPositionID  \
gameID playerID
6258   1802     count      63.000000       63.000000         63.000000
                mean     2299.541587    87626.095238          8.460317
                std      1514.027717    83751.633580          7.482938
                min       249.940000        0.000000          0.000000
                25%       690.310000      946.000000          0.500000
                50%      2087.810000    77888.000000         11.000000
                75%      3708.510000   196661.000000         14.000000
                max      5410.970000   201366.000000         21.000000
       1819     count      60.000000       60.000000         60.000000
                mean     4330.291500    74453.283333         12.683333
                std       779.288910    81156.640637          7.057852
                min         0.000000        0.000000          0.000000
                25%      3850.662500     1892.000000         10.750000
                50%      4425.555000    39442.000000         15.000000
                75%      4867.190000   135432.500000         17.000000
                max      5433.290000   204427.000000         21.000000
       1892     count     149.000000      149.000000        149.000000
                mean     2468.437517    89458.644295         13.798658
                std      1608.874397    73510.595766          5.385140
                min         1.310000        0.000000          0.000000
                25%      1053.380000    38433.000000         13.000000